"""description

Revision ID: df6a52c6d5d8
Revises: f4a6c50362ab
Create Date: 2026-04-23 06:22:24.593747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

# revision identifiers, used by Alembic.
revision: str = 'df6a52c6d5d8'
down_revision: Union[str, None] = 'f4a6c50362ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###